name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
        run: |
          mvn clean verify -Dspring.datasource.password=$SPRING_DATASOURCE_PASSWORD -Dbot.token=$BOT_TOKEN -Djwt.secret=$JWT_SECRET